# Generated by Django 5.1.2 on 2024-10-29 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Etudient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(max_length=20)),
                ('note', models.DecimalField(decimal_places=2, max_digits=2)),
            ],
        ),
    ]
