# Generated by Django 5.1.4 on 2024-12-19 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_remove_user_products_user_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='male',
            name='age_male',
            field=models.IntegerField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='male',
            name='n_enfant',
            field=models.IntegerField(max_length=20, null=True),
        ),
    ]
