# Generated by Django 5.1.4 on 2024-12-19 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_male_age_male_male_n_enfant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='male',
            old_name='age_male',
            new_name='age',
        ),
        migrations.RenameField(
            model_name='male',
            old_name='n_enfant',
            new_name='enfant',
        ),
        migrations.RenameField(
            model_name='male',
            old_name='name_male',
            new_name='name',
        ),
    ]
