# Generated by Django 5.1.4 on 2024-12-20 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_rename_age_male_male_age_rename_n_enfant_male_enfant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='male',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='photos/%y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='male',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='male',
            name='enfant',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='products',
            field=models.ManyToManyField(to='pages.product'),
        ),
    ]
