# Generated by Django 5.1.4 on 2024-12-21 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='products',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
