# Generated by Django 5.1.2 on 2024-10-29 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('content', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(max_length=40)),
                ('image', models.ImageField(upload_to='photos/%y/%m/%d')),
                ('ative', models.BooleanField(default=True)),
            ],
        ),
    ]
